/**
 * utils/exportFormats.js
 * Cookie export/import format handlers.
 *
 * Supported formats:
 *   - JSON (full cookie objects)
 *   - Netscape cookies.txt
 *   - Header (name=value; …) — for pasting into HTTP headers
 *   - Key=Value pairs (one per line)
 */

'use strict';

// eslint-disable-next-line no-unused-vars
const ExportFormats = (() => {

  /* =======================================================
     EXPORT — cookie[] → string
     ======================================================= */

  /**
   * Export cookies as pretty-printed JSON.
   * @param {chrome.cookies.Cookie[]} cookies
   * @returns {string}
   */
  function toJSON(cookies) {
    const data = cookies.map((c) => ({
      name:           c.name,
      value:          c.value,
      domain:         c.domain,
      path:           c.path,
      secure:         c.secure,
      httpOnly:       c.httpOnly,
      sameSite:       c.sameSite,
      expirationDate: c.expirationDate,
      hostOnly:       c.hostOnly,
      session:        c.session,
    }));
    return JSON.stringify(data, null, 2);
  }

  /**
   * Export cookies in Netscape cookies.txt format.
   * @param {chrome.cookies.Cookie[]} cookies
   * @returns {string}
   */
  function toNetscape(cookies) {
    const header = [
      '# Netscape HTTP Cookie File',
      '# Generated by Cookie Manager Chrome Extension',
      '#',
    ].join('\n');

    const lines = cookies.map((c) => {
      const domain     = c.domain || '';
      const subdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path       = c.path || '/';
      const secure     = c.secure ? 'TRUE' : 'FALSE';
      const expires    = c.expirationDate ? Math.round(c.expirationDate) : 0;
      const name       = c.name  || '';
      const value      = c.value || '';
      const domainField = c.httpOnly ? `#HttpOnly_${domain}` : domain;
      return [domainField, subdomains, path, secure, expires, name, value].join('\t');
    });

    return [header, ...lines].join('\n');
  }

  /**
   * Export cookies as an HTTP Cookie header value: name=value; name2=value2
   * @param {chrome.cookies.Cookie[]} cookies
   * @returns {string}
   */
  function toHeaderString(cookies) {
    return cookies.map((c) => `${c.name}=${c.value}`).join('; ');
  }

  /**
   * Export cookies as one name=value pair per line.
   * @param {chrome.cookies.Cookie[]} cookies
   * @returns {string}
   */
  function toPairs(cookies) {
    return cookies.map((c) => `${c.name}=${c.value}`).join('\n');
  }

  /* =======================================================
     PARSE / IMPORT — string → cookie-like object[]
     ======================================================= */

  /**
   * Parse cookies from a string in the specified format.
   * @param {string} data
   * @param {'json'|'netscape'|'pairs'} format
   * @returns {Array<{name:string, value:string, domain?:string, path?:string, secure?:boolean, httpOnly?:boolean, sameSite?:string, expirationDate?:number}>}
   */
  function parse(data, format) {
    switch (format) {
      case 'json':     return parseJSON(data);
      case 'netscape': return parseNetscape(data);
      case 'pairs':    return parsePairs(data);
      default:
        throw new Error(`Unsupported import format: "${format}"`);
    }
  }

  function parseJSON(data) {
    const parsed = JSON.parse(data);
    return Array.isArray(parsed) ? parsed : [parsed];
  }

  function parseNetscape(data) {
    const cookies = [];
    for (const line of data.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const parts = trimmed.split(/\t+/);
      if (parts.length >= 7) {
        cookies.push({
          domain:         parts[0],
          path:           parts[2],
          secure:         parts[3].toUpperCase() === 'TRUE',
          expirationDate: parseInt(parts[4], 10) || undefined,
          name:           parts[5],
          value:          parts[6],
        });
      }
    }
    return cookies;
  }

  function parsePairs(data) {
    const cookies = [];
    for (const line of data.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      const idx = trimmed.indexOf('=');
      if (idx > 0) {
        cookies.push({
          name:  trimmed.substring(0, idx).trim(),
          value: trimmed.substring(idx + 1).trim(),
        });
      }
    }
    return cookies;
  }

  /* =======================================================
     PUBLIC API
     ======================================================= */
  return {
    toJSON,
    toNetscape,
    toHeaderString,
    toPairs,
    parse,
  };
})();
